name: 'swap_controller_flutter'
description: 'swap_controller is program for help you, booster up your projects significants with amazing features and super easy for use'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/swap_controller'
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: 'flutter'
  plugin_platform_interface: '^2.0.2'
dev_dependencies:
  ffi: '^2.1.4'
  ffigen: '^17.0.0'
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
project:
  type: ''
  is_use_direct_package: true
  is_private: true
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  http:
    path: '../../../../../../.pub-cache/hosted/pub.dev/http-1.3.0'
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
repository: 'https://github.com/{github_username}/{repository_name}'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/{youtube_username}'
